/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jbm;

import java.awt.Frame;

/**
 *
 * @author akbarlaz
 */
public class FMain extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public FMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bBayarCicilan = new javax.swing.JLabel();
        bPembeli = new javax.swing.JLabel();
        bBeliTunai = new javax.swing.JLabel();
        bBeliKredit = new javax.swing.JLabel();
        bLaporanTunai = new javax.swing.JLabel();
        bLaporanCicilan = new javax.swing.JLabel();
        bLaporanKredit = new javax.swing.JLabel();
        bPengaturanStockMobil = new javax.swing.JLabel();
        bPengaturanPaketKredit = new javax.swing.JLabel();
        bPengaturanToko = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 700));
        setMinimumSize(new java.awt.Dimension(1280, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bBayarCicilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBayarCicilanMouseClicked(evt);
            }
        });
        getContentPane().add(bBayarCicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 450, 290, 50));

        bPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPembeliMouseClicked(evt);
            }
        });
        getContentPane().add(bPembeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 280, 50));

        bBeliTunai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBeliTunaiMouseClicked(evt);
            }
        });
        getContentPane().add(bBeliTunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 280, 50));

        bBeliKredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bBeliKreditMouseClicked(evt);
            }
        });
        getContentPane().add(bBeliKredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 280, 50));

        bLaporanTunai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLaporanTunaiMouseClicked(evt);
            }
        });
        getContentPane().add(bLaporanTunai, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 290, 50));

        bLaporanCicilan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLaporanCicilanMouseClicked(evt);
            }
        });
        getContentPane().add(bLaporanCicilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 290, 50));

        bLaporanKredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bLaporanKreditMouseClicked(evt);
            }
        });
        getContentPane().add(bLaporanKredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 380, 290, 50));

        bPengaturanStockMobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPengaturanStockMobilMouseClicked(evt);
            }
        });
        getContentPane().add(bPengaturanStockMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 430, 290, 50));

        bPengaturanPaketKredit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPengaturanPaketKreditMouseClicked(evt);
            }
        });
        getContentPane().add(bPengaturanPaketKredit, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 380, 290, 50));

        bPengaturanToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bPengaturanTokoMouseClicked(evt);
            }
        });
        getContentPane().add(bPengaturanToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 330, 290, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Desktop.png"))); // NOI18N
        background.setText("jLabel1");
        background.setMaximumSize(new java.awt.Dimension(1280, 700));
        background.setMinimumSize(new java.awt.Dimension(1280, 700));
        background.setPreferredSize(new java.awt.Dimension(1280, 700));
        background.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundMouseClicked(evt);
            }
        });
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        setSize(new java.awt.Dimension(1280, 700));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bBayarCicilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBayarCicilanMouseClicked
        // TODO add your handling code here:
        Frame fBC = new FBCicilan();
        fBC.show();
    }//GEN-LAST:event_bBayarCicilanMouseClicked

    private void bPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPembeliMouseClicked
        // TODO add your handling code here:
        Frame fP = new FPembeli();
        fP.show();
    }//GEN-LAST:event_bPembeliMouseClicked

    private void bBeliTunaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBeliTunaiMouseClicked
        // TODO add your handling code here:
        Frame fBT = new FBCash();
        fBT.show();
    }//GEN-LAST:event_bBeliTunaiMouseClicked

    private void bBeliKreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBeliKreditMouseClicked
        // TODO add your handling code here:
        Frame fBK = new FBKredit();
        fBK.show();
    }//GEN-LAST:event_bBeliKreditMouseClicked

    private void backgroundMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundMouseClicked

    private void bLaporanTunaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLaporanTunaiMouseClicked
        // TODO add your handling code here:
        Frame fLT = new FLCash();
        fLT.show();
    }//GEN-LAST:event_bLaporanTunaiMouseClicked

    private void bLaporanCicilanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLaporanCicilanMouseClicked
        // TODO add your handling code here:
        Frame fLC = new FLCicilan();
        fLC.show();
    }//GEN-LAST:event_bLaporanCicilanMouseClicked

    private void bLaporanKreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLaporanKreditMouseClicked
        // TODO add your handling code here:
        Frame fLK = new FLKredit();
        fLK.show();
    }//GEN-LAST:event_bLaporanKreditMouseClicked

    private void bPengaturanStockMobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPengaturanStockMobilMouseClicked
        // TODO add your handling code here:
        Frame fM = new FMobil();
        fM.show();
    }//GEN-LAST:event_bPengaturanStockMobilMouseClicked

    private void bPengaturanPaketKreditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPengaturanPaketKreditMouseClicked
        // TODO add your handling code here:
        Frame fPK = new FPKredit();
        fPK.show();
    }//GEN-LAST:event_bPengaturanPaketKreditMouseClicked

    private void bPengaturanTokoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPengaturanTokoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_bPengaturanTokoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bBayarCicilan;
    private javax.swing.JLabel bBeliKredit;
    private javax.swing.JLabel bBeliTunai;
    private javax.swing.JLabel bLaporanCicilan;
    private javax.swing.JLabel bLaporanKredit;
    private javax.swing.JLabel bLaporanTunai;
    private javax.swing.JLabel bPembeli;
    private javax.swing.JLabel bPengaturanPaketKredit;
    private javax.swing.JLabel bPengaturanStockMobil;
    private javax.swing.JLabel bPengaturanToko;
    private javax.swing.JLabel background;
    // End of variables declaration//GEN-END:variables
}
